use_frameworks!

platform :ios, '9.0'

target 'ComponentA_Category_Example' do
  pod 'ComponentA_Category', :path => '../'

  target 'ComponentA_Category_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
